CelPlace ClassPackage
celements/celements-crm pull request #4
Opened 2018-07-09 15:58 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-726

2018-07-09 16:05 UTC, msladek commented
please check that I moved all fields "correctly". some minor fixes/improvements to prettyName and validations

2018-07-11 07:38 UTC, dkhasham requested changes

2018-07-11 07:38 UTC, dkhasham commented on components/celplace/src/main/java/com/celements/crm/place/PlaceClasses.java
> +    needsUpdate |= bclass.addNumberField("isoNum", "iso country number code (three" + " digits)", 3,
if the string fits on one line there should no interruption with " + "

2018-07-11 11:33 UTC, dkhasham approved these changes

2018-07-11 11:33 UTC, merged